Form/Extension/ButtonIconExtension.php
<?php

namespace Admingenerator\GeneratorBundle\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ButtonIconExtension extends AbstractTypeExtension
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->setAttribute('icon', $options['icon']);
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['icon'] = $form->getConfig()->getAttribute('icon');
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'icon' => null,
        ));

        $resolver->setAllowedTypes(array(
            'icon' => array('null', 'string')
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getExtendedType()
    {
        return 'button';
    }
}

Form/Type/DateRangeType.php
<?php

namespace Admingenerator\GeneratorBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DateRangeType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        unset($options['years']);

        $options['from']['required'] = $options['required'];
        $options['to']['required'] = $options['required'];

        if ($options['format']) {
            $options['from']['format'] = $options['format'];
            $options['to']['format'] = $options['format'];
        }
        $options['from']['widget'] = 'single_text';
        $options['to']['widget'] = 'single_text';

        $builder
            ->add('from', new DateType(), $options['from'] + array(
                'label'              => 'date.from',
                'translation_domain' => 'Admingenerator',
            ))
            ->add('to', new DateType(), $options['to'] + array(
                'label'              => 'date.to',
                'translation_domain' => 'Admingenerator',
            ));
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'form';
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $years = range(date('Y'), date('Y') - 120);

        $resolver->setDefaults(array(
            'format' => null,
            'years'  => $years,
            'to'     => array('years' => $years, 'widget' => 'choice'),
            'from'   => array('years' => $years, 'widget' => 'choice'),
            'widget' => 'choice',
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'date_range';
    }
}

Form/Type/DateType.php
<?php

namespace Admingenerator\GeneratorBundle\Form\Type;

use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class DateType extends \Symfony\Component\Form\Extension\Core\Type\DateType
{

    /**
     * {@inheritdoc}
     */
    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['widget'] = $options['widget'];
        $pattern =  "d MMM y"; //$form->getConfig()->getAttribute('formatter')->getPattern();

        $view->vars['date_pattern'] = $pattern;
        $view->vars['dateFormat'] = $this->convertJqueryDate($pattern);
        $view->vars['locale'] = \Locale::getDefault();
    }

    protected function convertJqueryDate($format)
    {
        //jquery use a different syntax, have to replace
        //  php    jquery
        //  MM      mm
        //  MMM     M
        //  MMMM    MM
        //  y       yy

        if (strpos($format, "MMM") > 0) {
            $format = str_replace("MMM", "M", $format);
        } else {
            $format = str_replace("MM", "mm", $format);
        }
        $format = str_replace("LLL", "M", $format);
        $format = str_replace("y", "yy", $format);

        return $format;
    }

}

Form/Type/DoctrineODM/DoubleListType.php
<?php

namespace Admingenerator\GeneratorBundle\Form\Type\DoctrineODM;

use Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DoubleListType extends DocumentType
{
   /**
    * {@inheritdoc}
    */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);

        $resolver->replaceDefaults(array('multiple'=>true));
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'double_list';
    }
}

Form/Type/DoctrineORM/DoubleListType.php
<?php

namespace Admingenerator\GeneratorBundle\Form\Type\DoctrineORM;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DoubleListType extends EntityType
{
    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);

        $resolver->replaceDefaults(array('multiple'=>true));
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'double_list';
    }
}

Form/Type/Propel/DoubleListType.php
<?php

namespace Admingenerator\GeneratorBundle\Form\Type\Propel;

use Symfony\Bridge\Propel1\Form\Type\ModelType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DoubleListType extends ModelType
{
   /**
    * {@inheritdoc}
    */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);

        $resolver->replaceDefaults(array('multiple'=>true));
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'double_list';
    }

}

Resources/views/Form/fields.html.twig
{% use 'form_div_layout.html.twig' with choice_widget as base_choice_widget %}

{% block form_rows %}
{% spaceless %}
    {% if options is defined %}
        {% for child in form %}
            {{ form_row(child, options) }}
        {% endfor %}
    {% else %}
        {% for child in form %}
            {{ form_row(child) }}
        {% endfor %}
    {% endif %}
{% endspaceless %}
{% endblock form_rows %}

{% block form_row %}
{% spaceless %}
    <div class="row">
        <div class="input-field col s12 field-{{ form.vars.name }}{{ help ? ' with-help' }}{{ errors|length > 0 ? ' invalid'}}">
            {% if icon is defined and icon|trim is not empty %}
                <i class="mdi-{{ icon }} prefix"></i>
            {% endif %}

            {% set inputLabel %}
                <div class="input-label">
                    {{ form_label(form) }}
                    {{ block('form_help') }}
                </div>
            {% endset %}

            {% if inputLabel|striptags|trim %}
                {{ inputLabel }}
            {% endif %}
            <div class="input-input{{ not inputLabel|striptags|trim ? ' full' }}">
                {{ form_widget(form, errors|length > 0 ? {
                    'attr': attr|merge({
                        'class': attr.class|default('') ~ ' invalid'
                    })
                } : {}) }}
                {% if not inputLabel|striptags|trim and errors|length > 0 %}
                    {{ form_errors(form) }}
                {% endif %}
            </div>
        </div>
    </div>
{% endspaceless %}
{% endblock form_row %}

{% block form_label %}
{% spaceless %}
    {% if not compound %}
        {% set label_attr = label_attr|merge({'for': id}) %}
    {% endif %}
    {% if required %}
        {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
    {% endif %}
    {#{% if label is empty %}
        {% set label = name|humanize %}
    {% endif %}#}

    {% if errors|length > 0 %}
        {% set errs = [] %}
        {% for error in errors %}
            {% set errs = errs|merge([
                error.messagePluralization is null
                    ? error.messageTemplate|trans(error.messageParameters, 'validators')
                    : error.messageTemplate|transchoice(error.messagePluralization, error.messageParameters, 'validators')
            ]) %}
        {% endfor %}
        {% set label_attr = label_attr|merge({'data-error': errs|join('\n')}) %}
    {% endif %}

    <label onclick="" {% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>{{ label|trans({}, translation_domain) }}</label>
{% endspaceless %}
{% endblock form_label %}

{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
        <ul class="errors red-text">
            {% for error in errors %}
                <li>{{
                    error.messagePluralization is null
                        ? error.messageTemplate|trans(error.messageParameters, 'validators')
                        : error.messageTemplate|transchoice(error.messagePluralization, error.messageParameters, 'validators')
                }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endspaceless %}
{% endblock form_errors %}

{% block date_range_row %}
    {% spaceless %}
        <div class="form_row field_{{ form.vars.name }} field_date_range">
            {{ form_label(form) }}
            <div class="field_content">
                {{ form_errors(form) }}
                {{ form_widget(form) }}
            </div>
        </div>
    {% endspaceless %}
{% endblock date_range_row %}

{% block date_row %}
    {% spaceless %}
        {% set icon = 'i_calendar' %}
        {{ block('form_row') }}
    {% endspaceless %}
{% endblock date_row %}

{% block button_row %}
{% spaceless %}
    <div class="row">
        <div class="input-field col">
            {{ form_widget(form) }}
        </div>
    </div>
{% endspaceless %}
{% endblock button_row %}

{%- block button_widget -%}
    {%- if label is empty -%}
        {%- if label_format is not empty -%}
            {% set label = label_format|replace({
                '%name%': name,
                '%id%': id,
            }) %}
        {%- else -%}
            {% set label = name|humanize %}
        {%- endif -%}
    {%- endif -%}

    {% set attr = attr|merge({ 'class': 'cyan waves-effect waves-light btn' ~ (attr.class is defined ? attr.class : '') }) %}

    <button type="{{ type|default('button') }}" {{ block('button_attributes') }}>
        {{- translation_domain is same as(false) ? label : label|trans({}, translation_domain) -}}
        {%- if icon -%}
            <i class="mdi-content-{{ icon }} right"></i>
        {%- endif -%}
    </button>
{%- endblock button_widget -%}

{% block form_help %}
    {% if help %}
        <span class="form-help">
            {{- help -}}
        </span>
    {% endif %}
{% endblock form_help %}

{% block genemu_jquerycolor_javascript %}
    <script type="text/javascript" src="{{ asset('bundles/admingeneratorgenerator/js/colorpicker.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function($) {
            var $field = $('#{{ id }}');
            var $configs = $.extend({
                onBeforeShow: function() {
                    $(this).ColorPickerSetColor($field.val());
                }
            }, {{ configs|json_encode|raw }});

        {% if widget == "image" %}
            var $picker = $('#{{ id }}_color');

            $picker.ColorPicker($.extend({
                onChange: function(hsb, hex, rgb) {
                    $field.val(hex);
                }
            }, $configs));
        {% else %}
            $field.ColorPicker($.extend({
                onChange: function(hsb, hex, rgb) {
                    $field.val(hex);
                }
            }, $configs));
        {% endif %}
        });
    </script>
{% endblock genemu_jquerycolor_javascript %}

{% block genemu_jquerycolor_stylesheet %}
{% spaceless %}
    <link rel="stylesheet" href="{{ asset('bundles/admingeneratorgenerator/css/colorpicker.css') }}" />
    {% if widget == "image" %}
        <style type="text/css" media="screen">
            #{{ id }}_color {
                background: url({{ asset('bundles/genemuform/images/select.png') }});
                width: 36px;
                height: 36px;
                position: relative;
                overflow: hidden;
            }

            #{{ id }}_color div {
                background: url({{ asset('bundles/genemuform/images/select.png') }}) center center;
                position: absolute;
                left: 3px;
                top: 3px;
                width: 30px;
                height: 30px;
            }
        </style>
    {% endif %}
{% endspaceless %}
{% endblock genemu_jquerycolor_stylesheet %}